---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: dev
    backstage.io/kubernetes-namespace: dev
  name: dev-environment
spec:
  lifecycle: development
  owner: guests
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: dev01
    backstage.io/kubernetes-namespace: dev01
  name: dev01-environment
spec:
  lifecycle: development
  owner: guests
  type: environment
