apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: dev
    backstage.io/kubernetes-namespace: dev
  name: dev-environment
spec:
  lifecycle: development
  owner: guests
  type: environment
